# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 16:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('married_name', models.CharField(blank=True, max_length=50)),
                ('first_names', models.CharField(blank=True, max_length=75)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('aliases', models.CharField(blank=True, max_length=75)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=75)),
                ('type', models.CharField(choices=[('L', 'Letter'), ('E', 'Envelope'), ('T', 'Transcription'), ('D', 'Other document')], max_length=1)),
                ('image_file', models.ImageField(upload_to='letter_images')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('images', models.ManyToManyField(blank=True, to='letters.DocumentImage')),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=75)),
                ('date', django_date_extensions.fields.ApproximateDateField(null=True)),
                ('contents', tinymce.models.HTMLField(blank=True, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_date_extensions.fields.ApproximateDateField(null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('greeting', models.TextField(blank=True, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('closing', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('ps', models.TextField(blank=True, null=True)),
                ('complete_transcription', models.BooleanField(default=False)),
                ('notes', tinymce.models.HTMLField(blank=True)),
                ('language', models.CharField(blank=True, default='EN', max_length=2)),
                ('images', models.ManyToManyField(blank=True, to='letters.DocumentImage')),
            ],
        ),
        migrations.CreateModel(
            name='MiscDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75)),
                ('date', django_date_extensions.fields.ApproximateDateField(null=True)),
                ('contents', tinymce.models.HTMLField(blank=True, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True)),
                ('images', models.ManyToManyField(blank=True, to='letters.DocumentImage')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, default='US', max_length=2)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Represented as (longitude, latitude)', null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='miscdocument',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.Place'),
        ),
        migrations.AddField(
            model_name='miscdocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.DocumentSource'),
        ),
        migrations.AddField(
            model_name='miscdocument',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscdoc_writer', to='letters.Correspondent'),
        ),
        migrations.AddField(
            model_name='letter',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.Place'),
        ),
        migrations.AddField(
            model_name='letter',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='letters.Correspondent'),
        ),
        migrations.AddField(
            model_name='letter',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.DocumentSource'),
        ),
        migrations.AddField(
            model_name='letter',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='letters.Correspondent'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='letters.Place'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='images',
            field=models.ManyToManyField(blank=True, to='letters.DocumentImage'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='letters.Place'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_recipient', to='letters.Correspondent'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.DocumentSource'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_writer', to='letters.Correspondent'),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='images',
            field=models.ManyToManyField(blank=True, to='letters.DocumentImage'),
        ),
    ]
