# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:18
from __future__ import unicode_literals

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdocument',
            name='date',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True),
        ),
    ]
