# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:26
from __future__ import unicode_literals

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_auto_20170425_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='date',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, default=''),
        ),
    ]
