# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20170425_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='envelopes',
            field=models.ManyToManyField(blank=True, to='letters.Envelope'),
        ),
        migrations.AddField(
            model_name='miscdocument',
            name='envelopes',
            field=models.ManyToManyField(blank=True, to='letters.Envelope'),
        ),
    ]
