# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_auto_20170427_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='writer',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='letter_writer', to='letters.Correspondent'),
        ),
        migrations.AlterField(
            model_name='miscdocument',
            name='envelopes',
            field=models.ManyToManyField(blank=True, related_name='miscdoc', to='letters.Envelope'),
        ),
        migrations.AlterField(
            model_name='miscdocument',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='miscdoc', to='letters.DocumentImage'),
        ),
        migrations.AlterField(
            model_name='miscdocument',
            name='place',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='miscdoc', to='letters.Place'),
        ),
        migrations.AlterField(
            model_name='miscdocument',
            name='source',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='miscdoc', to='letters.DocumentSource'),
        ),
        migrations.AlterField(
            model_name='miscdocument',
            name='writer',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='miscdocument_writer', to='letters.Correspondent'),
        ),
    ]
