# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import letters.models.util


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0013_auto_20170508_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('NL', 'Dutch'), ('DE', 'German')], default=letters.models.util.Language('EN'), max_length=2),
        ),
        migrations.AlterField(
            model_name='letter',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('NL', 'Dutch'), ('DE', 'German')], default=letters.models.util.Language('EN'), max_length=2),
        ),
        migrations.AlterField(
            model_name='miscdocument',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('NL', 'Dutch'), ('DE', 'German')], default=letters.models.util.Language('EN'), max_length=2),
        ),
    ]
