# Generated by Django 3.0.14 on 2022-05-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0014_auto_20170508_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscdocument',
            options={'default_related_name': 'miscdoc'},
        ),
    ]
