# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_sentiment', '0003_auto_20170529_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='custom_sentiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='letter_sentiment.CustomSentiment'),
        ),
    ]
