# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_sentiment', '0005_term_analyzed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsentiment',
            name='max_weight',
            field=models.IntegerField(default=1),
        ),
    ]
