"""
Django settings for letterpress project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import letterpress.settings_secret as settings_secret

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings_secret.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = settings_secret.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_date_extensions',
    'django.forms',
    'sslserver',
    'tinymce',
    'letters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'letterpress.urls'

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 'django/forms/templates']
        ,
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'letterpress.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        # This engine supports geodatabase functionality in Django
        'ENGINE': 'django.contrib.gis.db.backends.spatialite',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# By default, staticfiles will look for files within the static/ directory of each installed app,
# as well as in directories defined in STATICFILES_DIRS.
STATIC_ROOT = os.path.join(BASE_DIR, 'letters/static')
STATIC_URL = '/static/'

# Configuration for django-tinymce
# Don't bother with TINYMCE_JS_ROOT and TINYMCE_JS_URL
# Just let it use the defaults and find everything in the django-tinymce install
TINYMCE_DEFAULT_CONFIG = {
    'plugins': 'paste,searchreplace',
    'theme': 'simple',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'valid_styles': {
        '*': 'text-decoration',
    },
    'browser_spellcheck': True,
    'forced_root_block': False,
}

# Compressor stopped working, maybe when I upgraded some other package or
# switched to django-sslserver, so I had to set it to false
TINYMCE_COMPRESSOR = False

# Where to find SpatiaLite and GDAL libraries, necessary to support geodatabase stuff in SQLite

# For Linux
SPATIALITE_LIBRARY_PATH = '/usr/local/lib/libspatialite.so'

# For Windows, use the following setting. Get mod_spatialite from http://www.gaia-gis.it/gaia-sins/
# Put all DLLs in the same directory with the Python executable (system and probably also virtualenv)
#SPATIALITE_LIBRARY_PATH = 'mod_spatialite'

# For Windows, set the location of the GDAL DLL and add the GDAL directory to your PATH for the other DLLs
# Under Linux it doesn't seem to be necessary
#GDAL_LIBRARY_PATH = 'C:\Program Files\GDAL\gdal201.dll'

# Security stuff

# SecurityMiddleware redirects all non-HTTPS requests to HTTPS (except for those URLs matching a regular
# expression listed in SECURE_REDIRECT_EXEMPT).
SECURE_SSL_REDIRECT = True
# Use a secure cookie for the session cookie
SESSION_COOKIE_SECURE = True
# Use a secure cookie for the CSRF cookie
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
# Set the HTTP Strict Transport Security header on all responses that do not already have it.
# When enabling HSTS, it's a good idea to first use a small value for testing, for example, SECURE_HSTS_SECONDS = 3600
# for one hour. Each time a Web browser sees the HSTS header from your site, it will refuse to communicate non-securely
# (using HTTP) with your domain for the given period of time. Once you confirm that all assets are served securely on
# your site (i.e. HSTS didn't break anything), it's a good idea to increase this value so that infrequent visitors will
# be protected (31536000 seconds, i.e. 1 year, is common).
SECURE_HSTS_SECONDS = 3600
# Do I want this or not?
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# For django.middleware.clickjacking.XFrameOptionsMiddleware, default is "SAMEORIGIN"
X_FRAME_OPTIONS = "DENY"





